name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop cicd-demo || true
            docker rm cicd-demo || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo
            docker run -d -p 3000:3000 --name cicd-demo ${{ secrets.DOCKER_USERNAME }}/cicd-demo
